Pierre/Models/Flavor.cs
using System.Collections.Generic;

namespace Pierre.Models
{
  public class Flavor
  {
    public Flavor()
    {
      JoinEntities = new HashSet<FlavorTreat>();
    }

    public int FlavorId { get; set; }
    public string Name { get; set; }
    public string FlavorProfile { get; set; }
    public virtual ApplicationUser User { get; set; }

    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
  }

  public enum Profile
  {
    Sweet,
    Salty,
    Bitter,
    Tangy,
    Sour,
    Spicy,
    Savory,
    Creamy,
    Fluffy
  }
}

Pierre/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Pierre.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Pierre.Controllers 
{
  [Authorize]
  public class FlavorsController : Controller 
  {
    private readonly PierreContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierreContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    
    public ActionResult Create()
    {
      return View();
    }

    
    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index", "Treats");
    }

    [AllowAnonymous]
    public ActionResult Details (int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Treat treat, int FlavorId)
    {
      if(FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Treats");
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if(TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Treats");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index", "Treats");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index", "Treats");
    }
  }
}

Pierre/Views/Flavors/AddTreat.cshtml
  
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h1>Add a treat to @Model.Name</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  @Html.Label("Select an existing Treat")
  @Html.DropDownList("TreatId")
  <input type="submit" value="Add" class="btn btn-warning"/>
}

<button class="btn btn-dark">@Html.ActionLink("Go back", "Details", new { id = @Model.FlavorId })</button>

Pierre/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}
@using Pierre.Models
@model Pierre.Models.Flavor

<h1 class="text-center">Create a Flavor</h1>
    @using (Html.BeginForm())
    {
      @Html.LabelFor(model => model.Name)
      @Html.TextBoxFor(model => model.Name, new { @class="form-control", @required="required" })

      @Html.LabelFor(model => model.FlavorProfile)
      @Html.DropDownListFor(model => model.FlavorProfile,  new SelectList(Enum.GetValues(typeof(Profile))), "Select Flavor Profile", new { @class="form-control", @required="required"})

      <input type="submit" value="Create" class="btn btn-success"/>
    }

<button class="btn btn-dark">@Html.ActionLink("Back to home", "Index", "Treats")</button>

Pierre/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Are you sure you want to delete your @Model.Name flavor?<h2>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-danger" />
}

<button class="btn btn-dark">@Html.ActionLink("Go back", "Details", new { id = @Model.FlavorId})</button>

Pierre/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}
@model Pierre.Models.Flavor
@using System.Security.Claims

<h1 class="text-center">Flavors: @Model.Name</h1>
<h3>Profile: @Model.FlavorProfile</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <h4>No treats have the @Model.Name flavor!</h4>
}
else
{
  <h3>Flavors:</h3>
  <ol>
    @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Treat.Name</li>
      @if (User.Identity.IsAuthenticated)
      {
        @using (Html.BeginForm("DeleteTreat", "Flavors"))
        {
          @Html.Hidden("joinId", @join.FlavorTreatId)
          <input type="submit" value="Delete" class="btn btn-danger"/>
        }
      }
    }
  </ol>
}

@if (User.Identity.IsAuthenticated)
{
  <button class="btn btn-dark">@Html.ActionLink("Edit Flavor", "Edit", new { id = @Model.FlavorId })</button>
  <button class="btn btn-danger">@Html.ActionLink("Delete Flavor", "Delete", new { id = @Model.FlavorId })</button>
  <button class="btn btn-dark">@Html.ActionLink("Add Treat", "AddTreat", new { id = @Model.FlavorId })</button>
  <button class="btn btn-dark">@Html.ActionLink("Go back", "Index", "Treats")</button>
}
else
{
  <p>Create an account to make your own treats and flavors!</p>
  <button class="btn btn-success">@Html.ActionLink("Register", "Register", "Account")</button>
  <button class="btn btn-dark">@Html.ActionLink("Go back", "Index", "Treats")</button>
}

Pierre/Views/Flavors/Edit.cshtml
  
@{
  Layout = "_Layout";
}
@using Pierre.Models
@model Pierre.Models.Flavor

<h1>Edit Flavor: @Model.Name</h1>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class="form-control" })
  @Html.LabelFor(model => model.FlavorProfile)
  @Html.DropDownListFor(model => model.FlavorProfile, new SelectList(Enum.GetValues(typeof(Profile))), "Select Flavor Profile", new { @class="form-control"})
  @Html.Label("Select an existing Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Edit" class="btn btn-warning"/>
}

<button class="btn btn-dark">@Html.ActionLink("Go back", "Details", new { id = @Model.FlavorId })</button>